services:

  # rabbitmq
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: gps_rabbitmq
    environment:
      -RABBITMQ_DEFAULT_USER=gps
      -RABBITMQ_DEFAULT_PASS=gps_pass
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - gps_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pgps_tracker_pass"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: gps_mysql
    environment:
      MYSQL_ROOT_PASSWORD: gps_tracker_pass
      MYSQL_DATABASE: gps_tracker
      MYSQL_USER: gps_user
      MYSQL_PASSWORD: gps_user_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - gps_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pgps_tracker_pass"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # MongoDB Database
  mongo:
    image: mongo:7.0
    container_name: gps_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_pass
      MONGO_INITDB_DATABASE: trackingDB
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - gps_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Elasticsearch
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: gps_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - gps_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: gps_redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gps_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # GPS Tracker Go Uygulaması
  gps-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gps_tracker_app
    ports:
      - "3000:3000"
    environment:
      - APP_PORT=3000
      - GIN_MODE=release
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DATABASE=trackingDB
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=gps_tracker
      - MYSQL_USER=root
      - MYSQL_PASSWORD=gps_tracker_pass
    networks:
      - gps_network
    depends_on:
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      mongo:
        condition: service_healthy
      mysql:
        condition: service_healthy
    restart: unless-stopped

# Persistent volumes
volumes:
  redis_data:
    driver: local
  elasticsearch_data:
    driver: local
  mongo_data:
    driver: local
  mysql_data:
    driver: local

# Custom network
networks:
  gps_network:
    driver: bridge